### ISSUE TITLE
Please specify the repositories licence(s)

### ISSUE THREAD

**Issue by cstrobbe** [openfed/AccessibilityCheckServer#95]
The repository does not contain an open-source licence. As a rule, code that has no open-source licence is not open source but a copyrighted work whose source code just happens to be publicly viewable.

To cite just one view on this type of situation (from [Alert: Almost 80% of GitLab Public Repositories are Not Open Source Licensed!](https://openweaver.medium.com/alert-almost-80-of-gitlab-public-repositories-are-not-open-source-licensed-a1b4cd8faf55)), 

> “No License” public repositories are more than a careless situation. They potentially promote copyright and software license violations. While the repository providers are slow in reacting to this clear and present danger, users and creators need to be extra vigilant in dealing with this.

According to the README file, AccessibilityCheckServer relies on technologies that include the following:

* [Angular](https://github.com/angular/components), which uses the MIT licence, 
* [pa11y](https://github.com/pa11y/pa11y), which uses the LGPL-3.0 licence,
* [simplecrawler](https://github.com/simplecrawler/), which BSD-2-Clause licence.

LGPL is less flexible the least flexible of these licences, but this should not be an issue if that code is not reused **in** the AccessibilityCheckServer. Nevertheless, some thought should be put in selecting a proper licence for the repository. I, for one, won't even touch the repo's code with a barge pole as long as it doesn't have a licence.

**Comment by rutiolma** [comment]
Thank you for the heads-up. We just added a license to the project.
